version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es01
    environment:
      - node.name=es01
    #内存锁设置 软限制和硬限制都为-1 --> es进程可以无限制使用内存
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wangli/workspace/elastic/elastic11/data:/usr/share/elasticsearch/data
      - /home/wangli/workspace/elastic/elastic11/config:/usr/share/elasticsearch/config
      - /home/wangli/workspace/elastic/elastic11/logs:/usr/share/elasticsearch/logs
    ports:
      - 19200:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es02
    environment:
      - node.name=es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wangli/workspace/elastic/elastic22/data:/usr/share/elasticsearch/data
      - /home/wangli/workspace/elastic/elastic22/config:/usr/share/elasticsearch/config
      - /home/wangli/workspace/elastic/elastic22/logs:/usr/share/elasticsearch/logs
    ports:
      - 29200:9200

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es03
    environment:
      - node.name=es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wangli/workspace/elastic/elastic33/data:/usr/share/elasticsearch/data
      - /home/wangli/workspace/elastic/elastic33/config:/usr/share/elasticsearch/config
      - /home/wangli/workspace/elastic/elastic33/logs:/usr/share/elasticsearch/logs
    ports:
      - 39200:9200

  kibana:
    image: kibana:7.17.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 15601:5601
    volumes:
      - /home/wangli/workspace/elastic/kibana/config:/usr/share/kibana/config

networks:
  default:
    external: true
    name: elastic-net
