version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    privileged: true
    # user: "jenkins:root"
    user: root
    # user: "jenkins:root"
    environment:
      - JENKINS_USER=root
      - JENKINS_GROUP=root
    ports:
      - 58080:8080
      - 50000:50000
    volumes:
      - "/home/ubuntu/www/cicd/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/usr/bin/docker:/usr/bin/docker"

networks:
  default:
    external: true
    name: jenkins-net