version: '3'
services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anxin123
    ports:
      - "53306:3306"
    volumes:
      - "/home/ubuntu/www/base/mysql/data:/var/lib/mysql"
      - "/home/ubuntu/www/base/mysql/conf:/etc/mysql/conf.d"
      - "/home/ubuntu/www/base/mysql/log:/var/log/mysql"
  nginx:
    image: "nginx:1.23.4"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/ubuntu/www/base/nginx/log:/var/log/nginx"
      - "/home/ubuntu/www/base/nginx/config:/etc/nginx"
      - "/home/ubuntu/www/base/nginx/dist:/usr/share/nginx/html"
    privileged: true

  redis:
    image: "redis:7.0"
    container_name: redis
    restart: always
    ports:
      - "56379:6379"
    volumes:
      - "/home/ubuntu/www/base/redis/data:/data"
      - "/home/ubuntu/www/base/redis/config/redis.conf:/usr/local/redis/config/redis.conf"
      - "/home/ubuntu/www/base/redis/logs:/logs"
    command: redis-server /usr/local/redis/config/redis.conf
networks:
  default:
    external: true
    name: anxin-net